export const GalleryData = [
    {
        id:1,
        titile:"travel",
        image:"./images/tv_khoailangthang.jpg"
    },
    {
        id:2,
        titile:"travel",
        image:"./images/tv_LyThanhCo.jpg"
    },
    {
        id:3,
        titile:"travel",
        image:"./images/tv_PhanTheAnh.jpg"
    },
    {
        id:4,
        titile:"travel",
        image:"./images/tv_LyThanhCo.jpg"
    },
    {
        id:5,
        titile:"beauty",
        image:"./images/tv_LyThanhCo.jpg"
    },
    {
        id:6,
        titile:"beauty",
        image:"./images/tv_LyThanhCo.jpg"
    },
    {
        id:7,
        titile:"FreeStyle",
        image:"./images/tv_LyThanhCo.jpg"
    },
    {
        id:8,
        titile:"fashion",
        image:"./images/tv_LyThanhCo.jpg"
    },
    {
        id:9,
        titile:"fashion",
        image:"./images/tv_LyThanhCo.jpg"
    },
]